/**
 * Helpers that lay Kotlin out the way ktlint's `ktlint_official` style does,
 * so generated files pass ktlint untouched.
 */

export const GENERATED_HEADER =
  "// @generated by @gale-plugin/codegen — do not edit";

const MAX_WIDTH = 140;
/** Where long strings are split, leaving room for indent and ` +`. */
const CHUNK_WIDTH = 100;

export function kotlinString(value: string): string {
  const escaped = value
    .replaceAll("\\", "\\\\")
    .replaceAll('"', '\\"')
    .replaceAll("$", "\\$")
    .replaceAll("\n", "\\n");
  return `"${escaped}"`;
}

/** A backtick test name built from a case name, without characters the JVM rejects. */
export function testName(prefix: string, name: string): string {
  const clean = `${prefix} ${name}`.replace(/[.;[\]/<>:\\`]/g, " ");
  return `\`${clean.replace(/\s+/g, " ").trim()}\``;
}

/**
 * `<indent><declaration> = "<value>"`, moved to the next line when it's too
 * long, and split into `+`-joined pieces when even that doesn't fit.
 */
export function kotlinStringAssignment(
  indent: string,
  declaration: string,
  value: string,
): string {
  const oneLine = `${indent}${declaration} = ${kotlinString(value)}`;
  if (oneLine.length <= MAX_WIDTH) {
    return oneLine;
  }
  const next = `${indent}    `;
  if (`${next}${kotlinString(value)}`.length <= MAX_WIDTH) {
    return `${indent}${declaration} =\n${next}${kotlinString(value)}`;
  }
  const pieces = chunk(value).map(kotlinString);
  const lines = pieces.map((piece, index) => {
    const pieceIndent = index === 0 ? next : `${next}    `;
    const join = index === pieces.length - 1 ? "" : " +";
    return `${pieceIndent}${piece}${join}`;
  });
  return [`${indent}${declaration} =`, ...lines].join("\n");
}

/** Splits text at spaces into pieces of at most `CHUNK_WIDTH` characters. */
function chunk(value: string): string[] {
  const pieces: string[] = [];
  let current = "";
  for (const word of value.split(/(?<= )/)) {
    if (current !== "" && current.length + word.length > CHUNK_WIDTH) {
      pieces.push(current);
      current = "";
    }
    current += word;
  }
  pieces.push(current);
  return pieces;
}
