/**
 * Helpers that lay Rust out the way rustfmt's defaults do, so generated files
 * pass `cargo fmt --check` untouched.
 */

export const GENERATED_HEADER =
  "// @generated by @gale-plugin/codegen — do not edit";

const MAX_WIDTH = 100;
/** rustfmt's `fn_call_width` and `array_width`. */
const ARGS_WIDTH = 60;
export const INDENT = "    ";

export function rustString(value: string): string {
  const escaped = value
    .replaceAll("\\", "\\\\")
    .replaceAll('"', '\\"')
    .replaceAll("\n", "\\n");
  return `"${escaped}"`;
}

export function rustOption(value: string | null): string {
  return value === null ? "None" : `Some(${rustString(value)})`;
}

/** A test function name built from a case name. */
export function snakeCase(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_|_$/g, "");
}

/**
 * `<indent><head>(<args>)<tail>` on one line when it fits, otherwise with one
 * argument per line. `macro` calls get no trailing comma, as rustfmt leaves them.
 */
export function rustCall(
  indent: string,
  head: string,
  args: readonly string[],
  tail: string,
  { macro = false } = {},
): string {
  return layout(indent, `${head}(`, args, `)${tail}`, macro ? "" : ",");
}

/** `<indent><head>vec![<items>]<tail>`, laid out like `rustCall`. */
export function rustVec(
  indent: string,
  head: string,
  items: readonly string[],
  tail: string,
): string {
  return layout(indent, `${head}vec![`, items, `]${tail}`, ",");
}

function layout(
  indent: string,
  open: string,
  items: readonly string[],
  close: string,
  trailingComma: string,
): string {
  const joined = items.join(", ");
  const line = `${indent}${open}${joined}${close}`;
  if (joined.length <= ARGS_WIDTH && line.length <= MAX_WIDTH) {
    return line;
  }
  const inner = `${indent}${INDENT}`;
  const body = items.map((item, index) =>
    index === items.length - 1
      ? `${inner}${item}${trailingComma}`
      : `${inner}${item},`,
  );
  return [`${indent}${open}`, ...body, `${indent}${close}`].join("\n");
}
