// @generated by @gale-plugin/codegen — do not edit

//! One test per shared case in `@gale-plugin/contract`.

use crate::contract::*;

fn platform(os: Os, arch: &str) -> Platform<'_> {
    Platform { os, arch }
}

fn settings(config_path: &str, binary_path: &str) -> PathSettings {
    PathSettings {
        config_path: config_path.to_string(),
        binary_path: binary_path.to_string(),
    }
}

fn probe(project_binary: Option<&str>, which: Option<&str>) -> Probe {
    Probe {
        project_binary: project_binary.map(str::to_string),
        which: which.map(str::to_string),
    }
}

#[test]
fn rust_target_macos_arm64() {
    let actual = rust_target(platform(Os::Darwin, "arm64"));
    assert_eq!(actual, Some("aarch64-apple-darwin"));
}

#[test]
fn rust_target_macos_x64() {
    let actual = rust_target(platform(Os::Darwin, "x64"));
    assert_eq!(actual, Some("x86_64-apple-darwin"));
}

#[test]
fn rust_target_linux_arm64() {
    let actual = rust_target(platform(Os::Linux, "arm64"));
    assert_eq!(actual, Some("aarch64-unknown-linux-gnu"));
}

#[test]
fn rust_target_linux_x64() {
    let actual = rust_target(platform(Os::Linux, "x64"));
    assert_eq!(actual, Some("x86_64-unknown-linux-gnu"));
}

#[test]
fn rust_target_windows_x64() {
    let actual = rust_target(platform(Os::Win32, "x64"));
    assert_eq!(actual, Some("x86_64-pc-windows-msvc"));
}

#[test]
fn rust_target_windows_arm64_has_no_release() {
    let actual = rust_target(platform(Os::Win32, "arm64"));
    assert_eq!(actual, None);
}

#[test]
fn rust_target_unknown_arch_has_no_release() {
    let actual = rust_target(platform(Os::Linux, "riscv64"));
    assert_eq!(actual, None);
}

#[test]
fn binary_file_name_macos_uses_gale() {
    let actual = binary_file_name(Os::Darwin);
    assert_eq!(actual, "gale");
}

#[test]
fn binary_file_name_linux_uses_gale() {
    let actual = binary_file_name(Os::Linux);
    assert_eq!(actual, "gale");
}

#[test]
fn binary_file_name_windows_uses_gale_exe() {
    let actual = binary_file_name(Os::Win32);
    assert_eq!(actual, "gale.exe");
}

#[test]
fn project_binary_path_macos_arm64() {
    let platform = platform(Os::Darwin, "arm64");
    let actual = project_binary_path(Some("/work/app"), platform);
    assert_eq!(
        actual.as_deref(),
        Some("/work/app/node_modules/@codebend3r/gale/bin/aarch64-apple-darwin/gale")
    );
}

#[test]
fn project_binary_path_linux_x64() {
    let platform = platform(Os::Linux, "x64");
    let actual = project_binary_path(Some("/home/dev/site"), platform);
    assert_eq!(
        actual.as_deref(),
        Some("/home/dev/site/node_modules/@codebend3r/gale/bin/x86_64-unknown-linux-gnu/gale")
    );
}

#[test]
fn project_binary_path_windows_uses_gale_exe() {
    let platform = platform(Os::Win32, "x64");
    let actual = project_binary_path(Some("/work/app"), platform);
    assert_eq!(
        actual.as_deref(),
        Some("/work/app/node_modules/@codebend3r/gale/bin/x86_64-pc-windows-msvc/gale.exe")
    );
}

#[test]
fn project_binary_path_root_with_a_trailing_slash() {
    let platform = platform(Os::Darwin, "arm64");
    let actual = project_binary_path(Some("/work/app/"), platform);
    assert_eq!(
        actual.as_deref(),
        Some("/work/app/node_modules/@codebend3r/gale/bin/aarch64-apple-darwin/gale")
    );
}

#[test]
fn project_binary_path_filesystem_root() {
    let platform = platform(Os::Darwin, "arm64");
    let actual = project_binary_path(Some("/"), platform);
    assert_eq!(
        actual.as_deref(),
        Some("/node_modules/@codebend3r/gale/bin/aarch64-apple-darwin/gale")
    );
}

#[test]
fn project_binary_path_no_workspace_root() {
    let platform = platform(Os::Darwin, "arm64");
    let actual = project_binary_path(None, platform);
    assert_eq!(actual.as_deref(), None);
}

#[test]
fn project_binary_path_platform_with_no_release() {
    let platform = platform(Os::Win32, "arm64");
    let actual = project_binary_path(Some("/work/app"), platform);
    assert_eq!(actual.as_deref(), None);
}

#[test]
fn resolve_binary_binary_path_setting_wins_over_project_and_path() {
    let settings = settings("", "/opt/gale/bin/gale");
    let probe = probe(
        Some("/work/app/node_modules/@codebend3r/gale/bin/aarch64-apple-darwin/gale"),
        Some("/usr/local/bin/gale"),
    );
    let actual = resolve_binary(&settings, probe);
    assert_eq!(actual.as_deref(), Some("/opt/gale/bin/gale"));
}

#[test]
fn resolve_binary_binary_path_setting_is_used_even_when_nothing_else_is_found() {
    let settings = settings("", "/opt/gale/bin/gale");
    let probe = probe(None, None);
    let actual = resolve_binary(&settings, probe);
    assert_eq!(actual.as_deref(), Some("/opt/gale/bin/gale"));
}

#[test]
fn resolve_binary_project_install_wins_over_path() {
    let settings = settings("", "");
    let probe = probe(
        Some("/work/app/node_modules/@codebend3r/gale/bin/aarch64-apple-darwin/gale"),
        Some("/usr/local/bin/gale"),
    );
    let actual = resolve_binary(&settings, probe);
    assert_eq!(
        actual.as_deref(),
        Some("/work/app/node_modules/@codebend3r/gale/bin/aarch64-apple-darwin/gale")
    );
}

#[test]
fn resolve_binary_path_is_used_when_the_project_has_no_install() {
    let settings = settings("", "");
    let probe = probe(None, Some("/usr/local/bin/gale"));
    let actual = resolve_binary(&settings, probe);
    assert_eq!(actual.as_deref(), Some("/usr/local/bin/gale"));
}

#[test]
fn resolve_binary_nothing_found() {
    let settings = settings("", "");
    let probe = probe(None, None);
    let actual = resolve_binary(&settings, probe);
    assert_eq!(actual.as_deref(), None);
}

#[test]
fn server_args_no_config_path() {
    let settings = settings("", "");
    let actual = server_args(&settings);
    let expected = vec!["--lsp"];
    assert_eq!(actual, expected);
}

#[test]
fn server_args_relative_config_path_is_passed_as_written() {
    let settings = settings("config/gale.json", "");
    let actual = server_args(&settings);
    let expected = vec!["--lsp", "--config", "config/gale.json"];
    assert_eq!(actual, expected);
}

#[test]
fn server_args_absolute_config_path() {
    let settings = settings("/etc/gale/gale.toml", "");
    let actual = server_args(&settings);
    let expected = vec!["--lsp", "--config", "/etc/gale/gale.toml"];
    assert_eq!(actual, expected);
}

#[test]
fn server_args_config_path_with_spaces_stays_one_argument() {
    let settings = settings("lint config/gale.json", "");
    let actual = server_args(&settings);
    let expected = vec!["--lsp", "--config", "lint config/gale.json"];
    assert_eq!(actual, expected);
}

#[test]
fn server_args_binary_path_does_not_change_the_arguments() {
    let settings = settings("", "/opt/gale/bin/gale");
    let actual = server_args(&settings);
    let expected = vec!["--lsp"];
    assert_eq!(actual, expected);
}
