// @generated by @gale-plugin/codegen — do not edit

//! Facts shared by every Gale editor plugin.

pub const SERVER_COMMAND: &str = "gale";
pub const LSP_ARG: &str = "--lsp";
pub const CONFIG_ARG: &str = "--config";

/// The `lsp.gale.settings` key that holds the config path.
pub const CONFIG_PATH_SETTING: &str = "configPath";

pub const NPM_PACKAGE_NAME: &str = "@codebend3r/gale";
pub const NPM_BIN_DIR: &str = "bin";

/// `(os, arch, rust target)` for every platform Gale publishes a binary for.
pub const PLATFORMS: &[(&str, &str, &str)] = &[
    ("darwin", "arm64", "aarch64-apple-darwin"),
    ("darwin", "x64", "x86_64-apple-darwin"),
    ("linux", "arm64", "aarch64-unknown-linux-gnu"),
    ("linux", "x64", "x86_64-unknown-linux-gnu"),
    ("win32", "x64", "x86_64-pc-windows-msvc"),
];

pub const MISSING_BINARY_MESSAGE: &str = "Gale couldn't find the gale binary. Install it in this project with `bun add -d @codebend3r/gale`, install it globally with `cargo install gale-lint`, or set `lsp.gale.binary.path` in settings.json.";
