// @generated by @gale-plugin/codegen — do not edit

package com.codebend3r.gale.core

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/** One test per shared case in `@gale-plugin/contract`. */
class ConformanceTest {
    @Test
    fun `rust target macOS arm64`() {
        assertEquals("aarch64-apple-darwin", rustTarget(Platform(Os.DARWIN, "arm64")))
    }

    @Test
    fun `rust target macOS x64`() {
        assertEquals("x86_64-apple-darwin", rustTarget(Platform(Os.DARWIN, "x64")))
    }

    @Test
    fun `rust target Linux arm64`() {
        assertEquals("aarch64-unknown-linux-gnu", rustTarget(Platform(Os.LINUX, "arm64")))
    }

    @Test
    fun `rust target Linux x64`() {
        assertEquals("x86_64-unknown-linux-gnu", rustTarget(Platform(Os.LINUX, "x64")))
    }

    @Test
    fun `rust target Windows x64`() {
        assertEquals("x86_64-pc-windows-msvc", rustTarget(Platform(Os.WIN32, "x64")))
    }

    @Test
    fun `rust target Windows arm64 has no release`() {
        assertNull(rustTarget(Platform(Os.WIN32, "arm64")))
    }

    @Test
    fun `rust target unknown arch has no release`() {
        assertNull(rustTarget(Platform(Os.LINUX, "riscv64")))
    }

    @Test
    fun `binary file name macOS uses gale`() {
        assertEquals("gale", binaryFileName(Os.DARWIN))
    }

    @Test
    fun `binary file name Linux uses gale`() {
        assertEquals("gale", binaryFileName(Os.LINUX))
    }

    @Test
    fun `binary file name Windows uses gale exe`() {
        assertEquals("gale.exe", binaryFileName(Os.WIN32))
    }

    @Test
    fun `resolve binary binary path setting wins over project and PATH`() {
        val settings = PathSettings("", "/opt/gale/bin/gale")
        val root = "/work/app"
        val platform = Platform(Os.DARWIN, "arm64")
        val probe = Probe(true, "/usr/local/bin/gale")
        val command = "/opt/gale/bin/gale"
        val expected = Resolution.Found(Source.SETTING, command)
        assertEquals(expected, resolveBinary(settings, root, platform, probe))
    }

    @Test
    fun `resolve binary binary path setting is used even when nothing else is found`() {
        val settings = PathSettings("", "/opt/gale/bin/gale")
        val root: String? = null
        val platform = Platform(Os.DARWIN, "arm64")
        val probe = Probe(false, null)
        val command = "/opt/gale/bin/gale"
        val expected = Resolution.Found(Source.SETTING, command)
        assertEquals(expected, resolveBinary(settings, root, platform, probe))
    }

    @Test
    fun `resolve binary project install wins over PATH`() {
        val settings = PathSettings("", "")
        val root = "/work/app"
        val platform = Platform(Os.DARWIN, "arm64")
        val probe = Probe(true, "/usr/local/bin/gale")
        val command = "/work/app/node_modules/@codebend3r/gale/bin/aarch64-apple-darwin/gale"
        val expected = Resolution.Found(Source.PROJECT, command)
        assertEquals(expected, resolveBinary(settings, root, platform, probe))
    }

    @Test
    fun `resolve binary project install on Linux x64`() {
        val settings = PathSettings("", "")
        val root = "/home/dev/site"
        val platform = Platform(Os.LINUX, "x64")
        val probe = Probe(true, null)
        val command = "/home/dev/site/node_modules/@codebend3r/gale/bin/x86_64-unknown-linux-gnu/gale"
        val expected = Resolution.Found(Source.PROJECT, command)
        assertEquals(expected, resolveBinary(settings, root, platform, probe))
    }

    @Test
    fun `resolve binary project install on Windows uses gale exe`() {
        val settings = PathSettings("", "")
        val root = "/work/app"
        val platform = Platform(Os.WIN32, "x64")
        val probe = Probe(true, null)
        val command = "/work/app/node_modules/@codebend3r/gale/bin/x86_64-pc-windows-msvc/gale.exe"
        val expected = Resolution.Found(Source.PROJECT, command)
        assertEquals(expected, resolveBinary(settings, root, platform, probe))
    }

    @Test
    fun `resolve binary PATH is used when the project has no install`() {
        val settings = PathSettings("", "")
        val root = "/work/app"
        val platform = Platform(Os.DARWIN, "arm64")
        val probe = Probe(false, "/usr/local/bin/gale")
        val command = "/usr/local/bin/gale"
        val expected = Resolution.Found(Source.PATH, command)
        assertEquals(expected, resolveBinary(settings, root, platform, probe))
    }

    @Test
    fun `resolve binary PATH is used when there is no workspace root`() {
        val settings = PathSettings("", "")
        val root: String? = null
        val platform = Platform(Os.DARWIN, "arm64")
        val probe = Probe(true, "/usr/local/bin/gale")
        val command = "/usr/local/bin/gale"
        val expected = Resolution.Found(Source.PATH, command)
        assertEquals(expected, resolveBinary(settings, root, platform, probe))
    }

    @Test
    fun `resolve binary PATH is used on a platform with no release`() {
        val settings = PathSettings("", "")
        val root = "/work/app"
        val platform = Platform(Os.WIN32, "arm64")
        val probe = Probe(true, "/usr/local/bin/gale")
        val command = "/usr/local/bin/gale"
        val expected = Resolution.Found(Source.PATH, command)
        assertEquals(expected, resolveBinary(settings, root, platform, probe))
    }

    @Test
    fun `resolve binary nothing found`() {
        val settings = PathSettings("", "")
        val root = "/work/app"
        val platform = Platform(Os.DARWIN, "arm64")
        val probe = Probe(false, null)
        val expected = Resolution.NotFound
        assertEquals(expected, resolveBinary(settings, root, platform, probe))
    }

    @Test
    fun `resolve binary nothing found on a platform with no release`() {
        val settings = PathSettings("", "")
        val root = "/work/app"
        val platform = Platform(Os.LINUX, "riscv64")
        val probe = Probe(true, null)
        val expected = Resolution.NotFound
        assertEquals(expected, resolveBinary(settings, root, platform, probe))
    }

    @Test
    fun `server args no config path`() {
        val settings = PathSettings("", "")
        assertEquals(listOf("--lsp"), serverArgs(settings))
    }

    @Test
    fun `server args relative config path is passed as written`() {
        val settings = PathSettings("config/gale.json", "")
        assertEquals(listOf("--lsp", "--config", "config/gale.json"), serverArgs(settings))
    }

    @Test
    fun `server args absolute config path`() {
        val settings = PathSettings("/etc/gale/gale.toml", "")
        assertEquals(listOf("--lsp", "--config", "/etc/gale/gale.toml"), serverArgs(settings))
    }

    @Test
    fun `server args config path with spaces stays one argument`() {
        val settings = PathSettings("lint config/gale.json", "")
        assertEquals(listOf("--lsp", "--config", "lint config/gale.json"), serverArgs(settings))
    }

    @Test
    fun `server args binary path does not change the arguments`() {
        val settings = PathSettings("", "/opt/gale/bin/gale")
        assertEquals(listOf("--lsp"), serverArgs(settings))
    }

    @Test
    fun `should restart gale json at the root`() {
        val settings = PathSettings("", "")
        assertTrue(shouldRestart("/work/app/gale.json", "/work/app", settings))
    }

    @Test
    fun `should restart gale toml at the root`() {
        val settings = PathSettings("", "")
        assertTrue(shouldRestart("/work/app/gale.toml", "/work/app", settings))
    }

    @Test
    fun `should restart stylelintrc at the root`() {
        val settings = PathSettings("", "")
        assertTrue(shouldRestart("/work/app/.stylelintrc", "/work/app", settings))
    }

    @Test
    fun `should restart stylelintrc json at the root`() {
        val settings = PathSettings("", "")
        assertTrue(shouldRestart("/work/app/.stylelintrc.json", "/work/app", settings))
    }

    @Test
    fun `should restart stylelintrc yml at the root`() {
        val settings = PathSettings("", "")
        assertTrue(shouldRestart("/work/app/.stylelintrc.yml", "/work/app", settings))
    }

    @Test
    fun `should restart stylelintrc yaml at the root`() {
        val settings = PathSettings("", "")
        assertTrue(shouldRestart("/work/app/.stylelintrc.yaml", "/work/app", settings))
    }

    @Test
    fun `should restart stylelint config js at the root`() {
        val settings = PathSettings("", "")
        assertTrue(shouldRestart("/work/app/stylelint.config.js", "/work/app", settings))
    }

    @Test
    fun `should restart stylelint config mjs at the root`() {
        val settings = PathSettings("", "")
        assertTrue(shouldRestart("/work/app/stylelint.config.mjs", "/work/app", settings))
    }

    @Test
    fun `should restart stylelint config cjs at the root`() {
        val settings = PathSettings("", "")
        assertTrue(shouldRestart("/work/app/stylelint.config.cjs", "/work/app", settings))
    }

    @Test
    fun `should restart stylelintrc js at the root`() {
        val settings = PathSettings("", "")
        assertTrue(shouldRestart("/work/app/.stylelintrc.js", "/work/app", settings))
    }

    @Test
    fun `should restart stylelintrc cjs at the root`() {
        val settings = PathSettings("", "")
        assertTrue(shouldRestart("/work/app/.stylelintrc.cjs", "/work/app", settings))
    }

    @Test
    fun `should restart stylelintrc mjs at the root`() {
        val settings = PathSettings("", "")
        assertTrue(shouldRestart("/work/app/.stylelintrc.mjs", "/work/app", settings))
    }

    @Test
    fun `should restart package json at the root`() {
        val settings = PathSettings("", "")
        assertTrue(shouldRestart("/work/app/package.json", "/work/app", settings))
    }

    @Test
    fun `should restart config file in a parent folder`() {
        val settings = PathSettings("", "")
        assertTrue(shouldRestart("/work/gale.json", "/work/app", settings))
    }

    @Test
    fun `should restart package json in a parent folder`() {
        val settings = PathSettings("", "")
        assertTrue(shouldRestart("/work/package.json", "/work/app", settings))
    }

    @Test
    fun `should restart config file at the filesystem root`() {
        val settings = PathSettings("", "")
        assertTrue(shouldRestart("/.stylelintrc", "/work/app", settings))
    }

    @Test
    fun `should restart config file in a subfolder`() {
        val settings = PathSettings("", "")
        assertFalse(shouldRestart("/work/app/src/gale.json", "/work/app", settings))
    }

    @Test
    fun `should restart config file in a sibling folder`() {
        val settings = PathSettings("", "")
        assertFalse(shouldRestart("/work/other/gale.json", "/work/app", settings))
    }

    @Test
    fun `should restart config file in a sibling folder sharing a name prefix`() {
        val settings = PathSettings("", "")
        assertFalse(shouldRestart("/work/app-old/gale.json", "/work/app", settings))
    }

    @Test
    fun `should restart unrelated file at the root`() {
        val settings = PathSettings("", "")
        assertFalse(shouldRestart("/work/app/styles.css", "/work/app", settings))
    }

    @Test
    fun `should restart backup of a config file`() {
        val settings = PathSettings("", "")
        assertFalse(shouldRestart("/work/app/gale.json.bak", "/work/app", settings))
    }

    @Test
    fun `should restart package json inside node_modules`() {
        val settings = PathSettings("", "")
        assertFalse(shouldRestart("/work/app/node_modules/some-pkg/package.json", "/work/app", settings))
    }

    @Test
    fun `should restart config path setting inside node_modules`() {
        val settings = PathSettings("node_modules/shared-config/gale.json", "")
        assertFalse(shouldRestart("/work/app/node_modules/shared-config/gale.json", "/work/app", settings))
    }

    @Test
    fun `should restart relative config path setting`() {
        val settings = PathSettings("config/lint.json", "")
        assertTrue(shouldRestart("/work/app/config/lint.json", "/work/app", settings))
    }

    @Test
    fun `should restart config path setting that leaves the root`() {
        val settings = PathSettings("../shared/gale.toml", "")
        assertTrue(shouldRestart("/work/shared/gale.toml", "/work/app", settings))
    }

    @Test
    fun `should restart absolute config path setting`() {
        val settings = PathSettings("/etc/gale/custom.json", "")
        assertTrue(shouldRestart("/etc/gale/custom.json", "/work/app", settings))
    }

    @Test
    fun `should restart other file next to the config path setting`() {
        val settings = PathSettings("config/lint.json", "")
        assertFalse(shouldRestart("/work/app/config/other.json", "/work/app", settings))
    }

    @Test
    fun `should restart config file at the root while a config path is set`() {
        val settings = PathSettings("config/lint.json", "")
        assertTrue(shouldRestart("/work/app/gale.json", "/work/app", settings))
    }
}
